version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: echo "A first hello"

  publish_package:
    docker:
      - image: golang:1.13.4-stretch
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - publish_package
